name: main_pr

on:
  workflow_call:
    secrets:
      PAT_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-source-branch:
    name: check-source-branch
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/check-source-branch@main
        with:
          allowed_branches: dev
          allowed_prefixes: hotfix/,release/,meta/,major/

  update-changelog:
    name: update-changelog
    runs-on: ubuntu-latest
    needs: [check-source-branch]
    outputs:
      did_push: ${{ steps.update-changelog.outputs.did_push || 'false' }}
    steps:
      - name: Update changelog
        id: update-changelog
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/update-changelog@main
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}
          gh_token: ${{ github.token }}

  format:
    name: format
    needs: [update-changelog]
    if: needs.update-changelog.outputs.did_push != 'true'
    runs-on: ubuntu-latest
    outputs:
      did_push: ${{ steps.format.outputs.did_push || 'false' }}
    steps:
      - name: Run format action
        id: format
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/format@main
        with:
          pat_token: ${{ secrets.PAT_TOKEN }}

  code-quality:
    name: code-quality
    runs-on: ubuntu-latest
    needs: [format]
    if: needs.format.outputs.did_push != 'true'
    steps:
      - name: Run code quality action
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/code-quality@main

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [code-quality]
    steps:
      - name: Run test action
        uses: j-moralejo-pinas/ci-cd-python-gitflow/.github/actions/test@main
